"""Generate paper-ready figures for Experiment 2 (target capture scenario).

Produces:
  - fig_exp2_angle.pdf     : four angle errors over time
  - fig_exp2_edge.pdf      : edge distances d12, d23, d34, d41
  - fig_exp2_coplanar.pdf  : coplanarity error
  - fig_exp2_norm.pdf      : undirected normal-direction error
  - fig_exp2_trajectory.pdf: 3-D trajectories with target
  - fig_exp2_tension.pdf   : cable tensions
  - fig_exp2_leso_x/y/z.pdf: already generated by main.py as PDF

Paper gains (nominal): k_theta=1.67, k_d=3.70, k_n=4.01, k_cop=4.47, k_v=7.53
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]  # code/
EXP2_DIR = Path(__file__).resolve().parent    # code/Exp_2/
for p in (str(ROOT), str(EXP2_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

from run import run as run_module
from run.run import _get_capture_point, _unit
from trajectory_plot.trajectory_plot import (
    plot_disturbance_by_axis,
    plot_3d_trajectory,
    set_output_dir,
)

# ── IEEE-compatible style ────────────────────────────────────────
plt.rc("font", size=7, family="serif")
plt.rc("axes", titlesize=8, labelsize=7)
plt.rc("xtick", labelsize=6)
plt.rc("ytick", labelsize=6)
plt.rc("legend", fontsize=6)
plt.rc("lines", linewidth=0.9, markersize=2.5)

COLORS = ["#2166AC", "#D6604D", "#4DAF4A", "#9467BD"]
LW = 0.8

FIGURES_DIR = (
    ROOT
    / ".."
    / "正文编写"
    / "myPaper_formationControl"
    / "figures"
).resolve()


def _common_ax(ax):
    ax.axhline(0, color="gray", linewidth=0.4, linestyle="--")
    ax.set_xlabel("Time (s)")
    ax.grid(True, linewidth=0.3, alpha=0.6)
    ax.tick_params(direction="in")


def _save(fig, name: str):
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGURES_DIR / f"{name}.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  saved {FIGURES_DIR / f'{name}.pdf'}")


def run_sim():
    runner = run_module.run(formation_flag_bool=True, use_leso=True)
    while runner.total_time < 85.0:
        runner.step_world()
    return runner


# ── individual figures ───────────────────────────────────────────

def fig_angle_error(runner):
    dt = runner.dt * runner.control_freq
    hist = runner.formation_control_law.formation_angle_error_history
    t = np.arange(len(hist["e_1"])) * dt
    names = ["e_1", "e_2", "e_3", "e_4"]
    labels = [
        r"$e_{\theta_1}$",
        r"$e_{\theta_2}$",
        r"$e_{\theta_3}$",
        r"$e_{\theta_4}$",
    ]

    fig, ax = plt.subplots(figsize=(3.5, 2.2))
    for name, label, c in zip(names, labels, COLORS):
        ax.plot(t, np.array(hist[name]), color=c, linewidth=LW, label=label)
    _common_ax(ax)
    ax.set_ylabel("Angle error (rad)")
    ax.legend(frameon=False, ncol=2, loc="upper right")
    _save(fig, "fig_exp2_angle")


def fig_edge_distance(runner):
    dt = runner.dt
    hist = runner.formation_control_law.edge_distance_history
    # edge names: edge12, edge23, edge34, edge41
    edge_names = ["edge12", "edge23", "edge34", "edge41"]
    labels = [r"$d_{12}$", r"$d_{23}$", r"$d_{34}$", r"$d_{41}$"]
    t = np.arange(len(hist["edge12"])) * dt

    fig, ax = plt.subplots(figsize=(3.5, 2.2))
    for name, label, c in zip(edge_names, labels, COLORS):
        ax.plot(t, np.array(hist[name]), color=c, linewidth=LW, label=label)
    _common_ax(ax)
    ax.set_ylabel("Edge distance (m)")
    ax.set_ylim(0.2, 1.2)
    ax.legend(frameon=False, ncol=2, loc="upper right")
    _save(fig, "fig_exp2_edge")


def fig_coplanar_error(runner):
    dt = runner.dt * runner.control_freq
    hist = np.array(runner.formation_control_law.Vol_hist)
    t = np.arange(len(hist)) * dt

    fig, ax = plt.subplots(figsize=(3.5, 2.2))
    ax.plot(t, hist, color=COLORS[0], linewidth=LW)
    _common_ax(ax)
    ax.set_ylabel(r"$e_{\mathrm{cop}}$")
    _save(fig, "fig_exp2_coplanar")


def fig_normal_error(runner):
    dt = runner.dt * runner.control_freq
    hist = np.array(runner.formation_control_law.norm_vector_error_hist)
    t = np.arange(len(hist)) * dt

    fig, ax = plt.subplots(figsize=(3.5, 2.2))
    ax.plot(t, hist, color=COLORS[0], linewidth=LW)
    _common_ax(ax)
    ax.set_ylabel(r"$\|e_n\|$")
    _save(fig, "fig_exp2_norm")


def fig_tension(runner):
    dt = runner.dt
    hist = runner.formation_control_law.Tension_history
    edge_names = ["edge12", "edge23", "edge34", "edge41"]
    labels = [r"$T_{12}$", r"$T_{23}$", r"$T_{34}$", r"$T_{41}$"]
    t = np.arange(len(hist["edge12"])) * dt

    fig, ax = plt.subplots(figsize=(3.5, 2.2))
    for name, label, c in zip(edge_names, labels, COLORS):
        ax.plot(t, np.array(hist[name]), color=c, linewidth=LW, label=label)
    _common_ax(ax)
    ax.set_ylabel("Tension (N)")
    ax.legend(frameon=False, ncol=2, loc="upper right")
    _save(fig, "fig_exp2_tension")


# ── main ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Running Exp_2 simulation...")
    runner = run_sim()
    print(f"Simulation done. total_time={runner.total_time:.1f}s")

    print("Generating paper figures...")
    set_output_dir(str(FIGURES_DIR))

    fig_angle_error(runner)
    fig_edge_distance(runner)
    fig_coplanar_error(runner)
    fig_normal_error(runner)
    fig_tension(runner)

    # 3-D trajectory with target drone
    idx_55 = int(round(55.0 / runner.dt))
    p_stack = np.vstack([
        np.array(a.history_pos[idx_55]) for a in runner.world.agent_list
    ])
    impact_point = _get_capture_point(p_stack, 0.25, -0.15)
    approach_dir = _unit(runner.v_target - runner.v_star)  # [-1, 0, 0] in NED
    start_point = impact_point - 2.5 * approach_dir + np.array([0.0, 0.0, 0.5])
    mid_point = impact_point - 1.0 * approach_dir + np.array([0.0, 0.5, 0.25])
    # smooth 3-point Bezier curve (quadratic)
    n_pts = 40
    tt = np.linspace(0, 1, n_pts)[:, None]
    tgt_traj = (1 - tt)**2 * start_point + 2 * (1 - tt) * tt * mid_point + tt**2 * impact_point

    plot_3d_trajectory(
        runner.world.agent_list,
        target_history=tgt_traj,
        t_snapshots=[0, 7, 20, 37, 55, 65, 85],
    )
    # Rename to paper figure name
    src = FIGURES_DIR / "trajectory_3d.pdf"
    dst = FIGURES_DIR / "fig_exp2_trajectory.pdf"
    if src.exists():
        dst.unlink(missing_ok=True)
        src.rename(dst)
        print(f"  renamed {src.name} -> {dst.name}")

    # LESO disturbance plots (already PDF)
    plot_disturbance_by_axis(runner.world.agent_list, runner.dt)

    print(f"\nAll figures saved to {FIGURES_DIR}")
